<footer>
  <ul class="odkaz">
    <li>Matěj Bartusek, Jakub Knapek, Martin Holub, 10. 6. 2023</li>
  </ul>
  <section>
    <div class="socky">
      <div class="soc">
        <img src="img/ig.png" alt="instagram">
        <a href="https://www.instagram.com/marvelstudios/" target="_blank">@marvelstudios
        </a>
      </div>
      <div class="soc">
        <img src="img/fb.png" alt="facebook">
        <a href="https://www.facebook.com/marvelstudios" target="_blank">Marvel Studios
        </a>
      </div>
      <div class="soc">
        <img src="img/tw.png" alt="twitter">
        <a href="https://twitter.com/marvelstudios?lang=cs" target="_blank">@MarvelStudios
        </a>
      </div>
    </div>
  </section>
</footer>