<!DOCTYPE html>
<?php
session_start();
?>
<html lang="cs-cz">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" type="image/jpg" href="img/mcu.ico" />
  <link rel="stylesheet" href="style/fotogalerie.css">
  <link rel="stylesheet" href="style/footer.css">
  <link rel="stylesheet" href="style/header.css">
  <title>FOTOGALERIE</title>
</head>

<body>
  <?php require("./view/header.phtml"); ?>
  <h1>Filmy</h1>
    <?php 
    $cols = -1;
    foreach ($movies as $movie) { 
      if ($cols == 3 && $cols != -1) {
        $cols = 0; ?>
        </div>
        <div class="group">
    <?php } else if ($cols == -1) { 
        $cols = 0; ?>
        <div class="group"> 
    <?php } ?>

    <div class="card">
      <div class="container">
        <h3><?= $movie["name"] ?></h3>
      </div>
      <img src="./img/uploaded/<?= $movie["img"] ?>" alt="plakát pro <?= $movie["name"] ?>" width="674px" height="1000px">
    </div>
    <?php $cols += 1; } ?>
  </div>
  </div>
  <h1>Seriály</h1>
  <div class="group">
    <?php foreach ($tvseries as $series) { ?>
    <div class="card">
      <div class="container">
        <h3><?= $series["name"] ?></h3>
      </div>
      <img src="./img/uploaded/<?= $series["img"] ?>" alt="plakát pro <?= $series["name"] ?>" width="674px" height="1000px">
    </div>
    <?php } ?>
  </div>
  <?php require("./view/footer.phtml"); ?>
</body>

</html>