<!DOCTYPE html>
<?php
session_start();
?>
<html lang="cs-cz">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" type="image/jpg" href="img/mcu.ico" />
  <link rel="stylesheet" href="style/fotogalerie.css">
  <link rel="stylesheet" href="style/footer.css">
  <link rel="stylesheet" href="style/header.css">
  <title>FOTOGALERIE</title>
</head>

<body>
  <?php require("./view/header.phtml"); ?>
  <h1>Filmy</h1>
  <div class="filmy"></div>
  <h1>Seriály</h1>
  <div class="serialy"></div>
  <?php require("./view/footer.phtml"); ?>
</body>

</html>