<!DOCTYPE html>

<html lang="cs-cz">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" type="image/jpg" href="img/mcu.ico" />
  <link rel="stylesheet" href="style/bootstrap.css">
  <link rel="stylesheet" href="style/account.css">
  <link rel="stylesheet" href="style/header.css">
  <title>MCU</title>
</head>

<body>
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card bg-dark">
          <div id="color">
            <div class="card-body p-5 text-center">
              <form method="POST" enctype="multipart/form-data" >
                <div class="mb-md-5 mt-md-4 pb-5">

                  <h2 class="fw-bold mb-2">PŘIDÁNÍ FILMU/SERIÁLU</h2>
                  <div class="form-outline mb-4">
                    <label class="form-label" for="name">Název</label>
                    <input type="text" name="name" id="name" class="form-control form-control-lg">
                  </div>

                  <div class="form-outline mb-4">
                    <label class="form-label" for="name">Vyber kategorii</label>
                    <select name="category" id="category" class="form-control">
                      <option value="movie">Film</option>
                      <option value="tvseries">Seriál</option>
                    </select>
                  </div>

                  <div class="form-outline mb-4">
                    <label class="form-label" for="password">Obrázek</label>
                    <input type="hidden" name="MAX_FILE_SIZE" value="1000000">
                    <input type="file" name="obr" id="obr" class="form-control-file">
                  </div>
                  <button class="btn btn-outline-light btn-lg px-5" type="submit"  name="submit" >Přidat</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

</html>